// Single source of truth for all native config. The `ios/` and `android/`
// folders are NOT committed; they get regenerated by `expo prebuild --clean`
// (both on EAS build servers and locally when needed).
//
// Per-profile env vars in eas.json control bundle ID / package / display name,
// so a `development` build produces com.kinderwell.app.dev and a `production`
// build produces com.kinderwell.app. See docs/DEV_PROD_ENVIRONMENTS.md.
module.exports = ({ config }) => {
  // Env-aware identity. Defaults are DEV-shaped: if nothing is set (fresh
  // clone, missing .env, etc.) we assume dev, not prod. Prod always sets its
  // own values explicitly via eas.json's `production` profile, so the safe
  // default is dev. See Fable review P1 #11.
  const iosBundleId = process.env.IOS_BUNDLE_ID || config.ios?.bundleIdentifier || 'com.kinderwell.app.dev';
  const androidPackage = process.env.ANDROID_PACKAGE || config.android?.package || 'com.kinderwell.app.dev';
  const appName = process.env.APP_DISPLAY_NAME || config.name || 'Kinderwell Dev';

  // Supabase host used for universal / app links (must match the project the
  // dev/prod build talks to). Falls back to DEV Supabase if the env var
  // isn't set.
  const supabaseHost = (process.env.SUPABASE_URL || 'https://xbkkjqvbsnroenqlqkmi.supabase.co').replace('https://', '');

  return {
    ...config,
    name: appName,
    ios: {
      ...config.ios,
      bundleIdentifier: iosBundleId,
      buildNumber: config.ios?.buildNumber ?? '9',
      supportsTablet: false,
      usesAppleSignIn: true,
      infoPlist: {
        ...config.ios?.infoPlist,
        // URL scheme for deep linking / OAuth callbacks. Matches bundle ID.
        CFBundleURLTypes: [
          { CFBundleURLSchemes: [iosBundleId] },
        ],
        // Match the pre-managed-workflow config we shipped in v1.0.0.
        NSAppTransportSecurity: {
          NSAllowsArbitraryLoads: false,
          NSAllowsLocalNetworking: true,
        },
        UIRequiredDeviceCapabilities: ['arm64'],
        UIRequiresFullScreen: false,
        UISupportedInterfaceOrientations: ['UIInterfaceOrientationPortrait'],
        UIUserInterfaceStyle: 'Light',
      },
      associatedDomains: [`applinks:${supabaseHost}`],
      // Full privacy manifest — reflects everything the app actually collects
      // (email, user ID, device ID, product interaction, crash data, purchase
      // history, name, other user content). Data types must be declared here
      // or App Store upload will be rejected.
      privacyManifests: {
        NSPrivacyAccessedAPITypes: [
          {
            NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategoryUserDefaults',
            NSPrivacyAccessedAPITypeReasons: ['CA92.1'],
          },
          {
            NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategoryFileTimestamp',
            NSPrivacyAccessedAPITypeReasons: ['C617.1', '0A2A.1', '3B52.1'],
          },
          {
            NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategorySystemBootTime',
            NSPrivacyAccessedAPITypeReasons: ['35F9.1'],
          },
          {
            NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategoryDiskSpace',
            NSPrivacyAccessedAPITypeReasons: ['E174.1', '85F4.1'],
          },
        ],
        NSPrivacyCollectedDataTypes: [
          {
            NSPrivacyCollectedDataType: 'NSPrivacyCollectedDataTypeEmailAddress',
            NSPrivacyCollectedDataTypeLinked: true,
            NSPrivacyCollectedDataTypeTracking: false,
            NSPrivacyCollectedDataTypePurposes: [
              'NSPrivacyCollectedDataTypePurposeAppFunctionality',
              'NSPrivacyCollectedDataTypePurposeAuthentication',
            ],
          },
          {
            NSPrivacyCollectedDataType: 'NSPrivacyCollectedDataTypeUserID',
            NSPrivacyCollectedDataTypeLinked: true,
            NSPrivacyCollectedDataTypeTracking: false,
            NSPrivacyCollectedDataTypePurposes: [
              'NSPrivacyCollectedDataTypePurposeAppFunctionality',
              'NSPrivacyCollectedDataTypePurposeAnalytics',
            ],
          },
          {
            NSPrivacyCollectedDataType: 'NSPrivacyCollectedDataTypeDeviceID',
            NSPrivacyCollectedDataTypeLinked: false,
            NSPrivacyCollectedDataTypeTracking: false,
            NSPrivacyCollectedDataTypePurposes: [
              'NSPrivacyCollectedDataTypePurposeAnalytics',
            ],
          },
          {
            NSPrivacyCollectedDataType: 'NSPrivacyCollectedDataTypeProductInteraction',
            NSPrivacyCollectedDataTypeLinked: true,
            NSPrivacyCollectedDataTypeTracking: false,
            NSPrivacyCollectedDataTypePurposes: [
              'NSPrivacyCollectedDataTypePurposeAppFunctionality',
              'NSPrivacyCollectedDataTypePurposeAnalytics',
              'NSPrivacyCollectedDataTypePurposeProductPersonalization',
            ],
          },
          {
            NSPrivacyCollectedDataType: 'NSPrivacyCollectedDataTypeCrashData',
            NSPrivacyCollectedDataTypeLinked: false,
            NSPrivacyCollectedDataTypeTracking: false,
            NSPrivacyCollectedDataTypePurposes: [
              'NSPrivacyCollectedDataTypePurposeAppFunctionality',
            ],
          },
          {
            NSPrivacyCollectedDataType: 'NSPrivacyCollectedDataTypePurchaseHistory',
            NSPrivacyCollectedDataTypeLinked: true,
            NSPrivacyCollectedDataTypeTracking: false,
            NSPrivacyCollectedDataTypePurposes: [
              'NSPrivacyCollectedDataTypePurposeAppFunctionality',
            ],
          },
          {
            NSPrivacyCollectedDataType: 'NSPrivacyCollectedDataTypeName',
            NSPrivacyCollectedDataTypeLinked: true,
            NSPrivacyCollectedDataTypeTracking: false,
            NSPrivacyCollectedDataTypePurposes: [
              'NSPrivacyCollectedDataTypePurposeAppFunctionality',
              'NSPrivacyCollectedDataTypePurposeProductPersonalization',
            ],
          },
          {
            NSPrivacyCollectedDataType: 'NSPrivacyCollectedDataTypeOtherUserContent',
            NSPrivacyCollectedDataTypeLinked: true,
            NSPrivacyCollectedDataTypeTracking: false,
            NSPrivacyCollectedDataTypePurposes: [
              'NSPrivacyCollectedDataTypePurposeAppFunctionality',
              'NSPrivacyCollectedDataTypePurposeProductPersonalization',
            ],
          },
        ],
        // ATT-classified tracking (cross-app for ad targeting): not used.
        NSPrivacyTracking: false,
      },
    },
    android: {
      ...config.android,
      package: androidPackage,
      intentFilters: [
        {
          action: 'VIEW',
          autoVerify: true,
          data: [{ scheme: 'https', host: supabaseHost }],
          category: ['BROWSABLE', 'DEFAULT'],
        },
      ],
    },
    plugins: [
      ...(config.plugins ?? []),
      // Notifications native config (permission strings, entitlements).
      // Package is installed via package.json; this line registers the plugin
      // so prebuild wires up native side.
      'expo-notifications',
      'expo-localization',
      // Sentry native crash + JS error reporting.
      '@sentry/react-native/expo',
    ],
    extra: {
      ...config.extra,
      supabaseUrl: process.env.SUPABASE_URL,
      supabaseAnonKey: process.env.SUPABASE_ANON_KEY,
      superwallApiKey: process.env.SUPERWALL_API_KEY,
      skipPaywall: process.env.SKIP_PAYWALL,
      posthogProjectToken: process.env.POSTHOG_PROJECT_TOKEN,
      posthogHost: process.env.POSTHOG_HOST || 'https://us.i.posthog.com',
      sentryDsn: process.env.SENTRY_DSN,
    },
  };
};
