#!/usr/bin/env bash
# Bump the Kinderwell version across the two files EAS/Metro read at build time.
#
# Usage:
#   ./scripts/bump-version.sh <new-marketing-version> <new-build-number>
#   ./scripts/bump-version.sh 1.2.0 10
#
# Managed workflow: the `ios/` and `android/` folders are NOT committed
# (they're regenerated by `expo prebuild --clean` on every EAS build), so the
# script only touches `app.json` and `package.json`. Info.plist +
# project.pbxproj — which the previous version of this script hardcoded —
# no longer exist in the repo. Attempting to run the old script exited with
# code 2 at the first grep (Fable review #7).
#
# Verifies before/after and refuses to run if the current state is drifted.
# See docs/VERSION_MANAGEMENT.md for the rules.

set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "Usage: $0 <new-marketing-version> <new-build-number>"
  echo "Example: $0 1.2.0 10"
  exit 1
fi

NEW_VERSION="$1"
NEW_BUILD="$2"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_JSON="$REPO_ROOT/app.json"
PACKAGE_JSON="$REPO_ROOT/package.json"

# Semver-ish sanity check on marketing version
if [[ ! "$NEW_VERSION" =~ ^[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]; then
  echo "Marketing version must look like 1.2.0 or 1.2 — got '$NEW_VERSION'" >&2
  exit 1
fi

if [[ ! "$NEW_BUILD" =~ ^[0-9]+$ ]]; then
  echo "Build number must be an integer — got '$NEW_BUILD'" >&2
  exit 1
fi

echo "Checking current versions..."

CURRENT_APP_JSON_VER=$(grep -E '"version"' "$APP_JSON" | head -1 | sed -E 's/.*"version": "([^"]+)".*/\1/')
CURRENT_APP_JSON_BUILD=$(grep -E '"buildNumber"' "$APP_JSON" | head -1 | sed -E 's/.*"buildNumber": "([^"]+)".*/\1/')
CURRENT_PACKAGE_VER=$(grep -E '^  "version"' "$PACKAGE_JSON" | head -1 | sed -E 's/.*"version": "([^"]+)".*/\1/')

echo "  app.json:            version=$CURRENT_APP_JSON_VER build=$CURRENT_APP_JSON_BUILD"
echo "  package.json:        version=$CURRENT_PACKAGE_VER"

# Refuse to run if marketing versions are already out of sync — the whole point
# of this script is to keep them synced, don't let a drift compound.
if [[ "$CURRENT_APP_JSON_VER" != "$CURRENT_PACKAGE_VER" ]]; then
  echo ""
  echo "ERROR: Current marketing versions don't match across files." >&2
  echo "  app.json:     $CURRENT_APP_JSON_VER" >&2
  echo "  package.json: $CURRENT_PACKAGE_VER" >&2
  echo "Fix the drift manually first, then re-run." >&2
  exit 1
fi

echo ""
echo "Bumping to version=$NEW_VERSION build=$NEW_BUILD..."

# app.json (uses Python json module to avoid corrupting the file)
python3 -c "
import json, sys
p = '$APP_JSON'
with open(p) as f: d = json.load(f)
d['expo']['version'] = '$NEW_VERSION'
d['expo']['ios']['buildNumber'] = '$NEW_BUILD'
with open(p, 'w') as f:
    json.dump(d, f, indent=2)
    f.write('\n')
"

# package.json — same trick
python3 -c "
import json
p = '$PACKAGE_JSON'
with open(p) as f: d = json.load(f)
d['version'] = '$NEW_VERSION'
with open(p, 'w') as f:
    json.dump(d, f, indent=2)
    f.write('\n')
"

echo ""
echo "Verifying after bump..."
NEW_APP_JSON_VER=$(grep -E '"version"' "$APP_JSON" | head -1 | sed -E 's/.*"version": "([^"]+)".*/\1/')
NEW_APP_JSON_BUILD=$(grep -E '"buildNumber"' "$APP_JSON" | head -1 | sed -E 's/.*"buildNumber": "([^"]+)".*/\1/')
NEW_PACKAGE_VER=$(grep -E '^  "version"' "$PACKAGE_JSON" | head -1 | sed -E 's/.*"version": "([^"]+)".*/\1/')

echo "  app.json:            version=$NEW_APP_JSON_VER build=$NEW_APP_JSON_BUILD"
echo "  package.json:        version=$NEW_PACKAGE_VER"

if [[ "$NEW_APP_JSON_VER" != "$NEW_VERSION" ]] || [[ "$NEW_PACKAGE_VER" != "$NEW_VERSION" ]]; then
  echo "ERROR: marketing version didn't apply everywhere" >&2
  exit 1
fi

if [[ "$NEW_APP_JSON_BUILD" != "$NEW_BUILD" ]]; then
  echo "ERROR: build number didn't apply everywhere" >&2
  exit 1
fi

echo ""
echo "✅ Version bumped to $NEW_VERSION (build $NEW_BUILD)"
echo "Next: git commit the changes, then run 'eas build --profile production --platform ios'"
